#!/bin/bash
# Wrapper script for ask-repo skill
# Runs the skill and automatically saves the walkthrough
# Usage: ask-repo.sh <github-url> "<question>"

set -e

GITHUB_URL="$1"
QUESTION="$2"

if [ -z "$GITHUB_URL" ] || [ -z "$QUESTION" ]; then
    echo "Usage: ask-repo.sh <github-url> \"<question>\""
    exit 1
fi

# Extract owner and repo from URL
REPO_PATH=$(echo "$GITHUB_URL" | sed -E 's|https?://github\.com/([^/]+)/([^/]+).*|\1-\2|')
REPO_DIR="$HOME/.ask-repo/$REPO_PATH"

# Clone if not exists
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ ! -d "$REPO_DIR" ]; then
    echo "Cloning $GITHUB_URL..."
    "$SCRIPT_DIR/clone_repo.sh" "$GITHUB_URL"
fi

# Generate topic from question
TOPIC=$(echo "$QUESTION" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9 ]//g' | tr ' ' '-' | sed 's/--*/-/g' | cut -c1-50)

echo "Analyzing repo..."

# Run Claude and capture output
OUTPUT=$(claude -p "You are analyzing the repo at $REPO_DIR

Question: $QUESTION

Instructions:
1. Read the relevant source files in $REPO_DIR
2. Explain how the code works
3. Include 3-5 code snippets with file:line references
4. Use relative links like [src/file.ts](../src/file.ts)

Format your response as a markdown document." --dangerously-skip-permissions 2>/dev/null)

# Save walkthrough
WALKTHROUGHS_DIR="$REPO_DIR/WALKTHROUGHS"
mkdir -p "$WALKTHROUGHS_DIR"

HEADER="# $QUESTION

> Generated by ask-repo on $(date +%Y-%m-%d)
> Repo: $GITHUB_URL

---

"

echo "$HEADER$OUTPUT" > "$WALKTHROUGHS_DIR/$TOPIC.md"

echo ""
echo "✓ Walkthrough saved: $WALKTHROUGHS_DIR/$TOPIC.md"
echo ""
echo "Open in Cursor:"
echo "  cursor $REPO_DIR"
echo "  cursor $WALKTHROUGHS_DIR/$TOPIC.md"
