#!/bin/bash
# Save a walkthrough to a repo's WALKTHROUGHS directory
# Usage: save-walkthrough.sh <repo-path> <topic> <content>
#
# Example:
#   save-walkthrough.sh ~/.ask-repo/pmndrs-zustand "state-management" "# How zustand..."
#
# Returns:
#   0 + filepath on success
#   1 + error on failure

set -e

REPO_PATH="$1"
TOPIC="$2"
CONTENT="$3"

# Validate inputs
if [ -z "$REPO_PATH" ] || [ -z "$TOPIC" ] || [ -z "$CONTENT" ]; then
    echo "ERROR: Missing required arguments"
    echo "Usage: save-walkthrough.sh <repo-path> <topic> <content>"
    exit 1
fi

# Expand ~ if present
REPO_PATH="${REPO_PATH/#\~/$HOME}"

# Check repo exists
if [ ! -d "$REPO_PATH" ]; then
    echo "ERROR: Repo not found at $REPO_PATH"
    echo "Run clone_repo.sh first"
    exit 1
fi

# Create WALKTHROUGHS directory
WALKTHROUGHS_DIR="$REPO_PATH/WALKTHROUGHS"
mkdir -p "$WALKTHROUGHS_DIR"

# Sanitize topic to kebab-case filename
FILENAME=$(echo "$TOPIC" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9-')
FILEPATH="$WALKTHROUGHS_DIR/$FILENAME.md"

# Add metadata header
DATE=$(date +%Y-%m-%d)
HEADER="<!-- Generated by ask-repo on $DATE -->
"

# Save content
echo "$HEADER$CONTENT" > "$FILEPATH"

# Verify file was created
if [ -f "$FILEPATH" ]; then
    echo "SUCCESS: Walkthrough saved to $FILEPATH"
    echo "$FILEPATH"
    exit 0
else
    echo "ERROR: Failed to save walkthrough"
    exit 1
fi
